export const products = [
  {
    id: 1,
    name: 'HP EliteBook 840 G6 14" Notebook - Core i7 i7-8565U - 16 GB RAM - 512 GB SSD - Windows 10 Pro - in-Plane Switching ',
    price: 1789.99,
    description: 'HP EB840G6 i7-8565U 14 16GB/512 PC Intel i7-8565U, 14. 0 FHD AG LED UWVA, UMA, Webcam, 16GB DDR4, 512GB SSD, abet, 3C Batt, FPR, W10 Pro64, 3yr Warty U. S',
    url: 'https://www.amazon.com/HP-EliteBook-840-Notebook-Plane/dp/B07VBHBRM1/ref=sr_1_5?dchild=1&qid=1614757285&rnid=13896617011&s=computers-intl-ship&sr=1-5',
    image: 'https://images-na.ssl-images-amazon.com/images/I/811p1jxp2pL._AC_SL1500_.jpg',
    image2: 'https://images-na.ssl-images-amazon.com/images/I/715k%2Bv%2BMAGL._AC_SL1500_.jpg',
    image3: 'https://images-na.ssl-images-amazon.com/images/I/7183sMUI6JL._AC_SL1500_.jpg',
    rating: '4.png',
    likes: 0,
    show: true,
    categoryId: 1
  },
  {
    id: 2,
    name: 'Microsoft Surface Laptop Go',
    price: 847,
    description: 'Sleek design and standout value. At just 2.44 pounds, it’s light, portable, and easy to keep by your side throughout the day.',
    url: 'https://www.amazon.com/Microsoft-Surface-Laptop-Touchscreen-Sandstone/dp/B08GZPDSF5/ref=sr_1_5?crid=2GD9704ZSJ6XU&dchild=1&keywords=laptops&pf_rd_i=21439846011&pf_rd_m=ATVPDKIKX0DER&pf_rd_p=516a7b4e-d342-442c-96c9-4fbeb114cb90&pf_rd_r=7K8RA04JFM4W4505WZSH&pf_rd_s=merchandised-search-4&pf_rd_t=101&qid=1614129334&sprefix=laptops%2Caps%2C236&sr=8-5',
    image: 'https://images-na.ssl-images-amazon.com/images/I/71Bih8dqq0L._AC_SL1500_.jpg',
    image2: 'https://images-na.ssl-images-amazon.com/images/I/71EVBJVMSoL._AC_SL1500_.jpg',
    image3: 'https://images-na.ssl-images-amazon.com/images/I/61cVhaXf0cL._AC_SL1500_.jpg',
    rating: '5.png',
    likes: 0,
    show: true,
    categoryId: 1
  },
  {
    id: 3,
    name: 'TS T14 AMD G1 R5 8G W10P',
    price: 889.99,
    description: 'Amazon.com Return Policy:You may return any new computer purchased from Amazon.com that is "dead on arrival," arrives in damaged condition, or is still in unopened boxes, for a full refund within 30 days of purchase.',
    image: 'https://images-na.ssl-images-amazon.com/images/I/514X2HBXYEL._AC_SL1280_.jpg',
    image2: 'https://images-na.ssl-images-amazon.com/images/I/416r5iHSZ7L._AC_SL1280_.jpg',
    image3: 'https://images-na.ssl-images-amazon.com/images/I/51zP1S9wZQL._AC_SL1280_.jpg',
    rating: '2.png',
    likes: 0,
    show: true,
    categoryId: 1
  },
  {
    id: 4,
    name: 'Apple MacBook Pro',
    price: 1218,
    description: 'New Apple MacBook Pro with Apple M1 Chip (13-inch, 8GB RAM, 256GB SSD Storage) - Space Gray (Latest Model). Get more done with up to 20 hours of battery life, the longest ever in a Mac.',
    url: 'https://www.amazon.com/Apple-MacBook-13-inch-256GB-Storage/dp/B08N5N6RSS?ref_=ast_sto_dp',
    image: 'https://images-na.ssl-images-amazon.com/images/I/81zKcC5wJ6L._AC_SL1500_.jpg',
    image2: 'https://images-na.ssl-images-amazon.com/images/I/913qQiDRZQL._AC_SL1500_.jpg',
    image3: 'https://images-na.ssl-images-amazon.com/images/I/71iGJlR9S5L._AC_SL1500_.jpg',
    rating: '5.png',
    likes: 0,
    show: true,
    categoryId: 1
  },
  {
    id: 5,
    name: 'Latitude 7420 2-in-1 I5 11-1145 G7 16GB 256GB SSD 14IN W10 WLS TCH',
    price: 1914.72,
    description: 'Amazon.com Return Policy:You may return any new computer purchased from Amazon.com that is "dead on arrival," arrives in damaged condition, or is still in unopened boxes, for a full refund within 30 days of purchase. Amazon.com reserves the right to test "dead on arrival" returns and impose a customer fee equal to 15 percent of the product sales price if the customer misrepresents the condition of the product. ',
    url: 'https://www.amazon.com/Latitude-7420-11-1145-16GB-256GB/dp/B08TY6GYV8/ref=sr_1_3?dchild=1&qid=1614757285&rnid=13896617011&s=computers-intl-ship&sr=1-3',
    image: 'https://images-na.ssl-images-amazon.com/images/I/51QbXhK%2B3nL._AC_.jpg',
    // image2: '',
    // image3: 'https://images-na.ssl-images-amazon.com/images/I/71bhWgQK-cL._AC_SL1500_.jpg',
    rating: '4.png',
    likes: 0,
    show: true,
    categoryId: 1
  },
  {
    id: 6,
    name: 'Facebook Portal Plus - Smart Video Calling 15.6” Touch Screen Display with Alexa - Black',
    price: 278.99,
    description: 'Easily video call with friends and family using your Messenger or WhatsApp account, even if they dont have Portal.',
    image: 'https://images-na.ssl-images-amazon.com/images/I/71a4UKUknlL._AC_SL1500_.jpg',
    image2: 'https://images-na.ssl-images-amazon.com/images/I/716q9DH%2BJbL._AC_SL1500_.jpg',
    image3: 'https://images-na.ssl-images-amazon.com/images/I/816Q0GIgV4L._AC_SL1500_.jpg',
    rating: '4.png',
    likes: 0,
    show: true,
    categoryId: 2
  },
  {
    id: 7,
    name: 'Echo Dot (3rd Gen) bundle with Amazon Smart Plug - Sandstone',
    price: 64.97,
    description: 'Includes Echo Dot (3rd gen) and Amazon Smart Plug – everything you need to start your smart home.',
    url: 'https://www.amazon.com/Echo-bundle-Amazon-Smart-Plug/dp/B07VB56W4D/ref=lp_21216812011_1_1?s=specialty-aps',
    image: 'https://images-na.ssl-images-amazon.com/images/I/61-ZaqPxznL._AC_SL1000_.jpg',
    image2: 'https://images-na.ssl-images-amazon.com/images/I/51hZ1Ix1bdL._AC_SL1000_.jpg',
    image3: 'https://images-na.ssl-images-amazon.com/images/I/61fLi7StjWL._AC_SL1000_.jpg',
    rating: '5.png',
    likes: 0,
    show: true,
    categoryId: 2
  },
  {
    id: 8,
    name: 'All-new Echo Dot (4th Gen) with clock - Glacier White - bundle with Sengled Bluetooth bulb (Certified for Humans product)',
    price: 59.99,
    description: 'This bundle contains Echo Dot (4th Gen) smart speaker with Clock and Sengled Bluetooth bulb',
    url: 'https://www.amazon.com/All-new-Echo-Dot-4th-clock/dp/B08K4FHQGM/ref=lp_21216812011_1_4?s=specialty-aps',
    image: 'https://images-na.ssl-images-amazon.com/images/I/51--6Qi8rnL._AC_.jpg',
    image2: 'https://images-na.ssl-images-amazon.com/images/I/71wkQ-VVeoL._AC_SL1000_.jpg',
    image3: 'https://images-na.ssl-images-amazon.com/images/I/51AhMebRWsL._AC_.jpg',
    rating: '4.png',
    likes: 0,
    show: true,
    categoryId: 2
  },
  {
    id: 9,
    name: 'Echo Show 5 Charcoal with Adjustable Stand',
    price: 84.55,
    description: 'Alexa can show you more – Compact 5.5” smart display ready to help manage your day, entertain at a glance, and connect you to friends and family.',
    url: 'https://www.amazon.com/Echo-Show-Charcoal-Adjustable-Stand/dp/B07SW188FP/ref=lp_21216812011_1_12?s=specialty-aps',
    image: 'https://images-na.ssl-images-amazon.com/images/I/61zsp4i71VL._AC_SL1000_.jpg',
    image2: 'https://images-na.ssl-images-amazon.com/images/I/61x5YHJhdCL._AC_SL1000_.jpg',
    image3: 'https://images-na.ssl-images-amazon.com/images/I/612FpAdPw7L._AC_SL1000_.jpg',
    rating: '4.png',
    likes: 0,
    show: true,
    categoryId: 2
  },
  {
    id: 10,
    name: 'Ring Video Doorbell – Satin Nickel with Ring Chime (2020 release)',
    price: 129.99,
    description: 'This bundle contains Ring Video Doorbell (2020 release) and Ring Chime (2020 release).',
    url: 'https://www.amazon.com/All-new-Ring-Video-Doorbell-release/dp/B087D8ZGFZ/ref=p13n_ds_purchase_sim_1p_dp_desktop_4?pd_rd_w=Ws3oL&pf_rd_p=aa96da76-5f67-44bb-853b-5d14d66e2ec7&pf_rd_r=VS2TEQRM0KT9584EEXDA&pd_rd_r=ca3dc6e5-0e35-4765-a25e-6c6f12d1a626&pd_rd_wg=zOqVN&pd_rd_i=B087D8ZGFZ&psc=1',
    image: 'https://images-na.ssl-images-amazon.com/images/I/51BlxeYdLsL._SL1000_.jpg',
    image2: 'https://images-na.ssl-images-amazon.com/images/I/61ayn-LiXwL._SL1000_.jpg',
    image3: 'https://images-na.ssl-images-amazon.com/images/I/51UTczONusL._SL1000_.jpg',
    rating: '5.png',
    likes: 0,
    show: true,
    categoryId: 2
  },
  {
    id: 11,
    name: '(Value Pack)',
    price: 15.99,
    description: 'IMMUNE SUPPORT: 100-count, 50mg Zinc Caplets for immune system health.The Zinc in Nature’s Bounty Zinc Caplets is a trace element that plays a vital role in immune support.NUMBER ONE BRAND: Natures Bounty is the number 1 brand for zinc supplements.',
    url: 'https://www.amazon.com/Natures-Bounty-Zinc-Caplets-100/dp/B000GCQ8X0/ref=sr_1_3?dchild=1&qid=1614757988&s=hpc-intl-ship&sr=1-3',
    image: 'https://images-na.ssl-images-amazon.com/images/I/71uFc4RbnWL._AC_SL1500_.jpg',
    image2: 'https://images-na.ssl-images-amazon.com/images/I/816CEOPSNvL._AC_SL1500_.jpg',
    image3: 'https://images-na.ssl-images-amazon.com/images/I/71B4gh9BxjL._AC_SL1500_.jpg',
    rating: '4.png',
    likes: 0,
    show: true,
    categoryId: 3
  },
  {
    id: 12,
    name: 'Quest Nutrition- High Protein, Low Carb, Gluten Free, Keto Friendly, 12-2.2 ounce assorted flavors variety Pack',
    price: 23.22,
    description: 'Certified Gluten-Free by the Gluten-Free Certification Organization.',
    url: 'https://www.amazon.com/Quest-Nutrition-Ultimate-Variety-Friendly/dp/B07J2MM23Z/ref=sr_1_7?dchild=1&qid=1614757987&s=hpc-intl-ship&sr=1-7',
    image: 'https://images-na.ssl-images-amazon.com/images/I/71SLUp0xilL._AC_SL1000_.jpg',
    image2: 'https://images-na.ssl-images-amazon.com/images/I/61LXu8tA3GL._AC_SL1000_.jpg',
    image3: 'https://images-na.ssl-images-amazon.com/images/I/717Axkw9fuL._AC_SL1000_.jpg',
    rating: '3.png',
    likes: 0,
    show: true,
    categoryId: 3
  },
  {
    id: 13,
    name: 'Teeth Whitening Pen, 20+ Uses, Effective, Painless, No Sensitivity, Travel-Friendly, Easy to Use, Beautiful White Smile, Natural Mint Flavor',
    price: 16.88,
    description: 'Remove Years of Stains. Our professional teeth whitening pen contains Carbamide Peroxide',
    url: 'https://www.amazon.com/Whitening-Effective-Sensitivity-Travel-Friendly-Beautiful/dp/B08GJBXDYQ/ref=sr_1_1_sspa?dchild=1&qid=1614758148&s=hpc-intl-ship&sr=1-1-spons&psc=1&spLa=ZW5jcnlwdGVkUXVhbGlmaWVyPUFNVERGOFQ0UE9PNUcmZW5jcnlwdGVkSWQ9QTA1NzIyNDQzNUdIUTVUVlZVRVUxJmVuY3J5cHRlZEFkSWQ9QTA3NTEyOTgxWVJBVlJZUUdUT1U4JndpZGdldE5hbWU9c3BfYXRmX2Jyb3dzZSZhY3Rpb249Y2xpY2tSZWRpcmVjdCZkb05vdExvZ0NsaWNrPXRydWU=',
    image: 'https://images-na.ssl-images-amazon.com/images/I/71S4BTTLhEL._AC_SL1500_.jpg',
    image2: 'https://images-na.ssl-images-amazon.com/images/I/711SWSdxXqL._AC_SL1500_.jpg',
    image3: 'https://images-na.ssl-images-amazon.com/images/I/71VM1j511iL._AC_SL1500_.jpg',
    rating: '2.png',
    likes: 0,
    show: true,
    categoryId: 3
  },
  {
    id: 14,
    name: 'Care Touch Lens Cleaning Wipes',
    price: 19.99,
    description: 'Streak-Free Formula: These wipes have a high-tech formula to clean effectively and dry quickly without leaving behind streaks or residue. It eliminates dust and',
    url: 'https://www.amazon.com/Care-Touch-Moistened-Cleansing-Eyeglasses/dp/B06WV8D6ZS/ref=sr_1_7?dchild=1&qid=1614758146&s=hpc-intl-ship&sr=1-7',
    image: 'https://images-na.ssl-images-amazon.com/images/I/71vbV63sneL._AC_SL1250_.jpg',
    image2: 'https://images-na.ssl-images-amazon.com/images/I/71H1knWcduL._AC_SL1250_.jpg',
    image3: 'https://images-na.ssl-images-amazon.com/images/I/61Lv8e9IPoL._AC_SL1250_.jpg',
    rating: '5.png',
    likes: 0,
    show: true,
    categoryId: 3
  },
  {
    id: 15,
    name: 'Kanjo Premium Acupressure Mat & Acupressure Pillow Set',
    price: 79.99,
    description: 'BENEFITS. Acupressure massage mats offer a simple yet effective at-home solution for back pain, neck pain, shoulder pain, headaches & migraine relief, improving blood circulation throughout the body, skin rejuvenation & helping to relieve tension. The included acupressure pillow provides additional relief and acupressure stimulation to the neck and upper back',
    url: 'https://www.amazon.com/Kanjo-Memory-Foam-Acupressure-Onyx/dp/B071LLNSS4/ref=sr_1_1_sspa?dchild=1&qid=1614758145&s=hpc-intl-ship&sr=1-1-spons&psc=1&spLa=ZW5jcnlwdGVkUXVhbGlmaWVyPUEyMDJWVDdVQTBYVVdVJmVuY3J5cHRlZElkPUEwNjM4ODc3U0lXSEtCUlNGVllCJmVuY3J5cHRlZEFkSWQ9QTAzNTc4MDgxM0s3SktDVzdPUENYJndpZGdldE5hbWU9c3BfYXRmX2Jyb3dzZSZhY3Rpb249Y2xpY2tSZWRpcmVjdCZkb05vdExvZ0NsaWNrPXRydWU=',
    image: 'https://images-na.ssl-images-amazon.com/images/I/91HS4vq7uvL._AC_SL1500_.jpg',
    image2: 'https://images-na.ssl-images-amazon.com/images/I/81%2BDRS0e8jL._AC_SL1500_.jpg',
    image3: 'https://images-na.ssl-images-amazon.com/images/I/71bZ6VAq-dL._AC_SL1500_.jpg',
    rating: '5.png',
    likes: 0,
    show: true,
    categoryId: 3
  },
  {
    id: 16,
    name: 'iOttie Easy One Touch 4 Dash & Windshield Car Mount Phone Holder Desk Stand Pad & Mat for iPhone',
    price: 24.95,
    description: 'Easy One Touch Lock/Release: Patented easy one touch mechanism allows quick one hand open and close operation',
    url: 'https://www.amazon.com/iOttie-Dashboard-Windshield-Samsung-Smartphone/dp/B076B27WP6/ref=sr_1_4?dchild=1&qid=1614758363&s=electronics&sr=1-4',
    image: 'https://images-na.ssl-images-amazon.com/images/I/718NVofDrCL._AC_SL1500_.jpg',
    image2: 'https://images-na.ssl-images-amazon.com/images/I/81YqefIFZDL._AC_SL1500_.jpg',
    image3: 'https://images-na.ssl-images-amazon.com/images/I/81n0-O8YU6L._AC_SL1500_.jpg',
    rating: '5.png',
    likes: 0,
    show: true,
    categoryId: 4
  },
  {
    id: 17,
    name: 'TQLGY 3 Pack Screen Protector and 3 Pack Camera Lens Protector Compatible with OnePlus Nord N100',
    price: 9.99,
    description: 'TQLGY Screen Protector and camera lens protector are compatible with OnePlus Nord N100, including 3 packs tempered glass screen protectors and 3 packs camera lens protectors. Protects your phone perfectly in all aspects.',
    url: 'https://www.amazon.com/TQLGY-Protector-Compatible-Tempered-Anti-Scratch/dp/B08QMWJN3H/ref=sr_1_2_sspa?dchild=1&qid=1614758360&s=electronics&sr=1-2-spons&psc=1&spLa=ZW5jcnlwdGVkUXVhbGlmaWVyPUEzM0MyNVBEWFAyMzgwJmVuY3J5cHRlZElkPUEwMTA1MjE2MjdDVzIySktUTVJGRCZlbmNyeXB0ZWRBZElkPUEwMzg4NTY0Mk1WMFJaRUU1R1ZZQiZ3aWRnZXROYW1lPXNwX2F0Zl9icm93c2UmYWN0aW9uPWNsaWNrUmVkaXJlY3QmZG9Ob3RMb2dDbGljaz10cnVl',
    image: 'https://images-na.ssl-images-amazon.com/images/I/71Kg5visRaL._AC_SL1500_.jpg',
    image2: 'https://images-na.ssl-images-amazon.com/images/I/71DoT-jwbfL._AC_SL1500_.jpg',
    // image3: '',
    rating: '5.png',
    likes: 0,
    show: true,
    categoryId: 4
  },
  {
    id: 18,
    name: 'Handheld 3-Axis Smartphone Gimbal Stabilizer with Grip Tripod Vlog YouTube Live Video for iPhone Android',
    price: 149.99,
    description: 'The magnetic phone clamp and magnetic ring holder enable effortless capture whenever inspiration strikes. Attach your smartphone to DJI OM 4 instantly, perfect for filming on the go.',
    url: 'https://www.amazon.com/DJI-OM-Handheld-Smartphone-Stabilizer/dp/B08CMVGVQY/ref=sr_1_11?dchild=1&qid=1614758362&s=electronics&sr=1-11',
    image: 'https://images-na.ssl-images-amazon.com/images/I/71yauPbL7KL._AC_SL1500_.jpg',
    image2: 'https://images-na.ssl-images-amazon.com/images/I/713S%2BI9xODL._AC_SL1500_.jpg',
    image3: 'https://images-na.ssl-images-amazon.com/images/I/81%2Bwnj5gDIL._AC_SL1500_.jpg',
    rating: '4.png',
    likes: 0,
    show: true,
    categoryId: 4
  },
  {
    id: 19,
    name: 'Led Video Lighting Kit Dimmable 5600K USB 70 LED Video Light with Mini Adjustable Tripod Stand and Color Filters for Table Top/Low Angle Photo Video Studio Shooting',
    price: 49.99,
    description: 'The small LED panel light',
    url: 'https://www.amazon.com/Lighting-Dimmable-Adjustable-Filters-Shooting/dp/B08DNMGNRK/ref=sr_1_3_sspa?dchild=1&qid=1614758362&s=electronics&sr=1-3-spons&psc=1&smid=A3AO9QDNU8GKEI&spLa=ZW5jcnlwdGVkUXVhbGlmaWVyPUFMVThSNlpGRDQwWlAmZW5jcnlwdGVkSWQ9QTA5NjEyOTkxNEIxN0Y0OFhLWUpUJmVuY3J5cHRlZEFkSWQ9QTA5OTI2NzYyVkNJWUNBMzUxWDk3JndpZGdldE5hbWU9c3BfYXRmX2Jyb3dzZSZhY3Rpb249Y2xpY2tSZWRpcmVjdCZkb05vdExvZ0NsaWNrPXRydWU=',
    image: 'https://images-na.ssl-images-amazon.com/images/I/611zzDaRgaL._AC_SL1154_.jpg',
    image2: 'https://images-na.ssl-images-amazon.com/images/I/61vs85nQlfL._AC_SL1200_.jpg',
    image3: 'https://images-na.ssl-images-amazon.com/images/I/71yGvf3JY0L._AC_SL1200_.jpg',
    rating: '2.png',
    likes: 0,
    show: true,
    categoryId: 4
  },
  {
    id: 20,
    name: 'DOLKSN Tesla Model 3 Center Screen Protector Tesla Model Y Center Screen Protector',
    price: 18.99,
    description: 'Notice Before Buying: Exclusive design for Tesla Mode 3 and for Tesla model Y, it is compatible with Tesla Model 3 and Model Y',
    url: 'https://www.amazon.com/DOLKSN-Protector-Tempered-Anti-Scratch-Resistant/dp/B08T6HGJL8/ref=sr_1_3_sspa?dchild=1&qid=1614758363&s=electronics&sr=1-3-spons&psc=1&spLa=ZW5jcnlwdGVkUXVhbGlmaWVyPUExQ1RCS0lCT1ZQMFFJJmVuY3J5cHRlZElkPUEwMjk5NTIxMTk1RVcxUFJHTEE0SyZlbmNyeXB0ZWRBZElkPUEwMzk3NzM3MUNINlpTRUNDNE0zSCZ3aWRnZXROYW1lPXNwX2F0Zl9icm93c2UmYWN0aW9uPWNsaWNrUmVkaXJlY3QmZG9Ob3RMb2dDbGljaz10cnVl',
    image: 'https://images-na.ssl-images-amazon.com/images/I/71lfAqxNuHL._AC_SL1500_.jpg',
    image2: 'https://images-na.ssl-images-amazon.com/images/I/61RYPwjoAUL._AC_SL1500_.jpg',
    image3: 'https://images-na.ssl-images-amazon.com/images/I/71XnBSbQfAL._AC_SL1500_.jpg',
    rating: '5.png',
    likes: 0,
    show: true,
    categoryId: 4
  }
];
